-- CÂU 2:
USE ADBTeam05SpatialDB
GO 


--CÂU A
SELECT MA AS MÃ,DIADIEM.STArea()*MATDONUOC*10000 AS N'LƯỢNG NƯỚC (M3)' FROM dbo.QUANLY
GO

--CÂU B
SELECT TOP 1 MA as N'Mã Đất',DIADIEM.STArea()*10000 AS N'DIỆN TÍCH (M2)'
FROM dbo.QUANLY
ORDER BY DIADIEM.STArea() ASC
GO

--CÂU C
DECLARE @KENH GEOMETRY=GEOMETRY::STGeomFromText('POLYGON((2 4,4 4,4 -2,2 -2,2 4))',4168)
SELECT MA AS N'Mã Đất',DIADIEM.STIntersection(@KENH).STArea()*10000 AS N'DIỆN TÍCH MẤT' FROM dbo.QUANLY
GO